nebius/api

nebius/iam/v1/group.proto
nebius/iam/v1/group_membership.proto
nebius/logging/v1/agentmanager/version_service.proto
nebius/msp/postgresql/v1alpha1/cluster.proto
nebius/msp/postgresql/v1alpha1/preset.proto
nebius/msp/v1alpha1/resource/template.proto
nebius/storage/v1/bucket_service.proto

This reverts commit b2a4620e9534c10ca70e6f39981794a8eb467506.

Revert "Publish proto files from 83e997b0c76 (#46)"

---

nebius/compute/v1/instance.proto

Automated sync PR from branch sync/74f0bd1e485

Sync: sync/74f0bd1e485

---

endpoints.md
nebius/iam/v1/static_key.proto
nebius/iam/v1/static_key_service.proto
nebius/registry/v1/registry.proto
nebius/vpc/v1/allocation.proto
nebius/vpc/v1/network.proto

Automated sync PR from branch sync/ab49e186222

Sync: sync/ab49e186222

---

endpoints.md
nebius/compute/v1/gpu_cluster.proto
nebius/compute/v1/instance.proto
nebius/iam/v1/access_permit.proto
nebius/iam/v1/access_permit_service.proto
nebius/iam/v1/group_service.proto
nebius/iam/v2/access_key.proto
nebius/iam/v2/access_key_service.proto
nebius/msp/postgresql/v1alpha1/cluster_service.proto

Automated sync PR from branch sync/c363ad9d560

Sync: sync/c363ad9d560

---

nebius/logging/v1/agentmanager/version_service.proto

Automated sync PR from branch sync/daf89c4f751

Sync: sync/daf89c4f751

---

nebius/storage/v1/bucket.proto

Automated sync PR from branch sync/da908972e99

Sync: sync/da908972e99

---

nebius/msp/postgresql/v1alpha1/backup_service.proto
nebius/msp/postgresql/v1alpha1/cluster_service.proto
nebius/msp/v1alpha1/resource/preset_service.proto
nebius/msp/v1alpha1/resource/template_service.proto

Automated sync PR from branch sync/46847450e95

Sync: sync/46847450e95

---

endpoints.md
nebius/audit/v2/access_token.proto
nebius/audit/v2/audit_event.proto
nebius/audit/v2/audit_event_service.proto
nebius/audit/v2/authentication.proto
nebius/audit/v2/authentication_type.proto
nebius/audit/v2/authorization.proto
nebius/audit/v2/federation.proto
nebius/audit/v2/request.proto
nebius/audit/v2/resource.proto
nebius/audit/v2/resource_metadata.proto
nebius/audit/v2/resource_state.proto
nebius/audit/v2/response.proto
nebius/audit/v2/service.proto
nebius/audit/v2/static_key.proto
nebius/audit/v2/status.proto
nebius/audit/v2/subject.proto

Automated sync PR from branch sync/1b983a48d8b

Sync: sync/1b983a48d8b

---

nebius/msp/postgresql/v1alpha1/cluster_service.proto
nebius/vpc/v1/network_service.proto
nebius/vpc/v1/pool_service.proto
nebius/vpc/v1/subnet_service.proto

Automated sync PR from branch sync/bb3b0da5baf

Sync: sync/bb3b0da5baf

---

nebius/audit/v2/audit_event_service.proto

Automated sync PR from branch sync/858b6658b55

Sync: sync/858b6658b55

---

nebius/compute/v1/disk.proto
nebius/compute/v1/image.proto
nebius/iam/v1/container.proto
nebius/iam/v1/project_service.proto

Automated sync PR from branch sync/00530dd2ed1

Sync: sync/00530dd2ed1

---

nebius/annotations.proto
nebius/logging/v1/agentmanager/version_service.proto

Automated sync PR from branch sync/05fd0dc0d8d

Sync: sync/05fd0dc0d8d

---

endpoints.md
nebius/msp/serverless/v1alpha1/endpoint.proto
nebius/msp/serverless/v1alpha1/endpoint_service.proto
nebius/msp/serverless/v1alpha1/job.proto
nebius/msp/serverless/v1alpha1/job_service.proto
nebius/msp/v1alpha1/common.proto

Automated sync PR from branch sync/03a4a0d05d1

Sync: sync/03a4a0d05d1

---

nebius/iam/v1/project_service.proto
nebius/iam/v1/tenant_service.proto
nebius/msp/postgresql/v1alpha1/backup_service.proto
nebius/msp/serverless/v1alpha1/endpoint.proto
nebius/msp/serverless/v1alpha1/job.proto

Automated sync PR from branch sync/7c72d5ff523

Sync: sync/7c72d5ff523

---

nebius/compute/v1/instance.proto
nebius/compute/v1alpha1/instance.proto
nebius/mk8s/v1/cluster_service.proto
nebius/msp/postgresql/v1alpha1/backup_service.proto

Automated sync PR from branch sync/80fb073f11c

Sync: sync/80fb073f11c

---

nebius/msp/mlflow/v1alpha1/cluster.proto

Automated sync PR from branch sync/b0e6502ce44

Sync: sync/b0e6502ce44

---

endpoints.md
nebius/compute/v1/disk.proto
nebius/compute/v1/disk_service.proto
nebius/compute/v1/filesystem.proto
nebius/compute/v1/filesystem_service.proto
nebius/compute/v1/gpu_cluster.proto
nebius/compute/v1/gpu_cluster_service.proto
nebius/compute/v1/image_service.proto
nebius/compute/v1/instance.proto
nebius/compute/v1/instance_service.proto
nebius/compute/v1/platform_service.proto
nebius/storage/v1alpha1/transfer.proto
nebius/storage/v1alpha1/transfer_service.proto

Automated sync PR from branch sync/1e4d85e4be5

Sync: sync/1e4d85e4be5

---

endpoints.md
nebius/annotations.proto
nebius/audit/v2/audit_event_service.proto
nebius/compute/v1/filesystem.proto
nebius/compute/v1/maintenance_event.proto
nebius/compute/v1/maintenance_service.proto
nebius/storage/v1alpha1/transfer_service.proto
nebius/vpc/v1/allocation_service.proto
nebius/vpc/v1/network_service.proto
nebius/vpc/v1/pool_service.proto
nebius/vpc/v1/subnet_service.proto
nebius/vpc/v1alpha1/allocation_service.proto
nebius/vpc/v1alpha1/network_service.proto
nebius/vpc/v1alpha1/pool_service.proto
nebius/vpc/v1alpha1/scope_service.proto
nebius/vpc/v1alpha1/subnet_service.proto

Automated sync PR from branch sync/1d757d16c11

Sync: sync/1d757d16c11

---

endpoints.md
nebius/audit/v2/request.proto
nebius/audit/v2/response.proto

Automated sync PR from branch sync/ac23065de6b

Sync: sync/ac23065de6b

---

endpoints.md
nebius/billing/v1alpha1/calculator.proto
nebius/billing/v1alpha1/calculator_service.proto
nebius/compute/v1/node_service.proto

Automated sync PR from branch sync/414c819cfb2

Sync: sync/414c819cfb2

---

nebius/mk8s/v1/node_group.proto
nebius/mk8s/v1alpha1/node_group.proto

Automated sync PR from branch sync/d4688017e07

Sync: sync/d4688017e07

---

nebius/common/v1/metadata.proto
nebius/compute/v1/disk.proto
nebius/compute/v1/instance.proto
nebius/compute/v1/node_service.proto
nebius/mk8s/v1/node_group.proto
nebius/mk8s/v1alpha1/node_group.proto
nebius/registry/v1/registry.proto

Automated sync PR from branch sync/bcdd23782e3

Sync: sync/bcdd23782e3

---

nebius/compute/v1/instance.proto

Automated sync PR from branch sync/bb97bc7936b

Sync: sync/bb97bc7936b

---

endpoints.md
nebius/compute/v1/platform.proto
nebius/iam/v1/federated_credentials_service.proto

Automated sync PR from branch sync/bb8fd26281d

Sync: sync/bb8fd26281d

---

nebius/iam/v1/federated_credentials.proto

Automated sync PR from branch sync/6bd81df0fe6

Sync: sync/6bd81df0fe6

---

nebius/annotations.proto
nebius/billing/v1alpha1/calculator_service.proto
nebius/common/v1/operation_service.proto
nebius/common/v1alpha1/operation_service.proto
nebius/compute/v1/maintenance_service.proto
nebius/compute/v1/node_service.proto
nebius/logging/v1/agentmanager/version_service.proto
nebius/msp/postgresql/v1alpha1/backup_service.proto
nebius/storage/v1alpha1/transfer_service.proto
nebius/vpc/v1/allocation_service.proto
nebius/vpc/v1/pool_service.proto
nebius/vpc/v1/subnet_service.proto
nebius/vpc/v1alpha1/subnet_service.proto

Automated sync PR from branch sync/5d72355cf44

Sync: sync/5d72355cf44

---

nebius/audit/v2/request.proto

Automated sync PR from branch sync/0526eccfc12

Sync: sync/0526eccfc12

---

nebius/common/v1/resource_event.proto

Automated sync PR from branch sync/38f30f7de

Sync: sync/38f30f7de

---

nebius/common/v1/resource_event.proto
nebius/iam/v2/access_key.proto
nebius/iam/v2/access_key_service.proto
nebius/mk8s/v1/node_group.proto

Automated sync PR from branch sync/bcf405e58

Sync: sync/bcf405e58

---

nebius/compute/v1/network_interface.proto
nebius/vpc/v1alpha1/network_interface.proto

Automated sync PR from branch sync/fd71e6ed0

Sync: sync/fd71e6ed0

---

nebius/logging/v1/agentmanager/version_service.proto
nebius/storage/v1alpha1/transfer.proto

Automated sync PR from branch sync/3fbb2258c

Sync: sync/3fbb2258c

---

nebius/compute/v1/platform.proto
nebius/storage/v1/s3_events.proto
nebius/vpc/v1/allocation.proto
nebius/vpc/v1/allocation_service.proto
nebius/vpc/v1/network.proto
nebius/vpc/v1/network_service.proto
nebius/vpc/v1/pool.proto
nebius/vpc/v1/pool_service.proto
nebius/vpc/v1/subnet.proto
nebius/vpc/v1/subnet_service.proto

Automated sync PR from branch sync/80c45cdb6

Sync: sync/80c45cdb6
